version: '3.8'

services:
  api:
    image: rajshakerp/housepricepredictor/dev:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/api:/app/src/api
      - ./models:/app/models
      - ./configs:/app/configs
    command: uvicorn main:app --host 0.0.0.0 --port 8000